package com.tg.skillsmatrix.Type;

public enum SkillGeneralEnum {
    RISK_MANAGEMENT,
    GOVERNANCE,
    ASSET_MANAGEMENT,
    ACCESS_CONTROL,
    SECURITY_MONITORING,
    INCIDENT_RESPONSE,
    SECURE_CONFIGURATION,
    USER_EDUCATION_AND_AWARENESS,
    MALWARE_PROTECTION,
    SECURE_NETWORK_CONFIGURATION,
    REMOVABLE_MEDIA_CONTROLS,
    INCIDENT_MANAGEMENT,
    SECURE_SOFTWARE_DEVELOPMENT,
    DATA_PROTECTION,
    MONITORING_AND_DETECTION,
    NETWORK_SEGMENTATION,
    BACKUP_AND_RECOVERY,
    SUPPLY_CHAIN_SECURITY,
    PHYSICAL_SECURITY,
    VULNERABILITY_MANAGEMENT

}
